/* =============================================================================
 * core/synthload.js - build a LoadSet from twelve monthly bills.
 *
 * Pure ES module, no network, runs in the browser and in Node 24.
 *
 * Why: a household with no Green Button file still has a bill every month.  We
 * can spread each month's kWh over its hours with a typical home's daily shape.
 * The result is a LoadSet the engine cannot tell from a parsed one (same `ts`
 * strings, same DST days, Float64Array kwh, no export), flagged by
 * `meta.source: "synthetic"` so the UI can say how much less certain it is.
 *
 * How the shape is chosen: for each calendar month there is a weekday and a
 * weekend 24-hour profile (each sums to 1) plus a weekend-day to weekday-day
 * energy ratio.  A month's kWh is split across its days by that ratio (calendar
 * weekdays vs Saturdays and Sundays; holidays count as weekdays, we do not guess)
 * and each day's share across its hours by the profile.  Month totals are exact.
 *
 * DST follows core/greenbutton.js: the spring-forward day has 23 slots (the parsers
 * leave out the 01:00 label, see tests/greenbutton.test.mjs and the demo files), the
 * fall-back day has 24 slots and its 01:00 slot stands for two real hours, so it
 * carries double weight.  US rules; zones that do not observe DST get none.
 *
 * Limits are in docs/synthetic-load.md: the shapes come from ONE real home
 * (the demo household, Agoura Hills) with its EV removed, so there is no
 * special-case treatment of air-conditioning-heavy inland homes, EVs or pools.
 * =========================================================================== */
import { _internal as GBI } from "./greenbutton.js";

// ---------------------------------------------------------------- shapes
// Generated by `node tests/tools/derive-synth-shapes.mjs` on 2026-10-04 from
// data/demo/*.csv (parsed with core/greenbutton.js, merged, detected EV subtracted
// with flexload.detectEV).  WEEKDAY / WEEKEND: per calendar month (Jan..Dec), the
// share of that day's kWh in each clock hour 0..23.  WEEKEND_RATIO: a weekend
// day's kWh divided by a weekday's, same month.  MONTH_SHARE: each month's share
// of annual kWh (daily average x days in month, normalised).  Only shapes are
// kept, never the household's own kWh.
const WEEKDAY = [
  [0.02369, 0.02452, 0.02546, 0.0244, 0.02626, 0.02613, 0.03019, 0.04915, 0.04175, 0.03917, 0.04711, 0.04375, 0.04638, 0.04283, 0.0509, 0.05787, 0.0565, 0.06925, 0.05592, 0.05193, 0.04802, 0.0435, 0.04115, 0.03418],
  [0.02336, 0.0218, 0.02542, 0.02264, 0.02571, 0.02421, 0.0346, 0.06639, 0.0476, 0.03623, 0.03528, 0.03621, 0.04291, 0.04292, 0.04446, 0.05643, 0.05107, 0.05612, 0.05841, 0.05957, 0.0575, 0.05398, 0.04283, 0.03433],
  [0.02054, 0.019, 0.01809, 0.01827, 0.01739, 0.01728, 0.01879, 0.0481, 0.03481, 0.03152, 0.04144, 0.03914, 0.03953, 0.04475, 0.05339, 0.06589, 0.07107, 0.07537, 0.07332, 0.06749, 0.06197, 0.05129, 0.04072, 0.03082],
  [0.02237, 0.0197, 0.02006, 0.01964, 0.02149, 0.023, 0.02482, 0.04973, 0.03785, 0.03179, 0.05305, 0.04361, 0.04782, 0.05199, 0.0584, 0.05406, 0.0573, 0.06441, 0.06013, 0.05735, 0.05772, 0.04882, 0.04113, 0.03378],
  [0.02045, 0.01936, 0.01721, 0.01576, 0.0166, 0.01499, 0.0152, 0.04148, 0.02978, 0.02773, 0.0288, 0.03286, 0.04009, 0.04101, 0.05288, 0.07129, 0.08179, 0.0838, 0.08061, 0.07237, 0.0643, 0.05507, 0.04274, 0.03383],
  [0.02834, 0.02151, 0.01853, 0.0146, 0.01403, 0.01351, 0.01295, 0.02969, 0.02348, 0.02079, 0.02261, 0.02771, 0.0375, 0.04715, 0.05477, 0.06661, 0.077, 0.09003, 0.08468, 0.08046, 0.06749, 0.05915, 0.04828, 0.03914],
  [0.02548, 0.02197, 0.02015, 0.01565, 0.01297, 0.01288, 0.01122, 0.01825, 0.01976, 0.02039, 0.02399, 0.03231, 0.0421, 0.05676, 0.06205, 0.07058, 0.08175, 0.08337, 0.08166, 0.07298, 0.0687, 0.06081, 0.04805, 0.03619],
  [0.02692, 0.02213, 0.02055, 0.01554, 0.01299, 0.01276, 0.01023, 0.01755, 0.01841, 0.02024, 0.02417, 0.033, 0.04446, 0.05484, 0.06785, 0.07582, 0.08463, 0.08407, 0.08104, 0.0731, 0.06508, 0.05498, 0.04443, 0.03522],
  [0.02174, 0.01848, 0.01581, 0.01539, 0.01428, 0.01175, 0.01079, 0.02658, 0.02125, 0.02167, 0.02531, 0.03645, 0.0464, 0.05837, 0.06907, 0.07632, 0.08716, 0.08493, 0.07849, 0.07216, 0.06403, 0.05194, 0.0413, 0.03033],
  [0.02537, 0.02267, 0.02027, 0.02133, 0.0196, 0.01871, 0.02119, 0.04603, 0.03517, 0.03333, 0.0327, 0.03315, 0.03758, 0.04504, 0.05154, 0.06294, 0.07334, 0.07792, 0.06917, 0.06742, 0.06315, 0.04916, 0.04011, 0.03312],
  [0.02575, 0.02681, 0.02456, 0.02588, 0.0257, 0.02571, 0.03057, 0.05649, 0.04684, 0.03936, 0.03758, 0.04165, 0.04364, 0.04926, 0.05584, 0.06023, 0.05035, 0.05968, 0.05238, 0.05114, 0.04757, 0.04509, 0.04194, 0.03596],
  [0.02974, 0.02496, 0.02514, 0.02571, 0.02587, 0.02771, 0.02829, 0.04227, 0.03966, 0.03535, 0.03997, 0.04087, 0.03977, 0.0421, 0.04781, 0.04699, 0.05565, 0.06508, 0.06114, 0.0594, 0.05554, 0.05022, 0.04873, 0.04202],
];
const WEEKEND = [
  [0.02384, 0.0254, 0.02438, 0.02675, 0.02599, 0.03367, 0.02955, 0.03597, 0.04986, 0.04822, 0.0489, 0.05076, 0.05073, 0.04954, 0.04557, 0.04856, 0.04777, 0.06686, 0.05001, 0.05155, 0.05118, 0.04246, 0.03783, 0.03465],
  [0.02383, 0.02411, 0.02452, 0.02468, 0.02489, 0.02634, 0.03205, 0.04035, 0.04789, 0.04605, 0.05112, 0.04459, 0.05112, 0.05231, 0.05197, 0.05501, 0.05114, 0.05305, 0.05234, 0.05273, 0.05178, 0.04706, 0.03966, 0.03141],
  [0.0222, 0.01778, 0.01759, 0.02199, 0.02346, 0.01925, 0.02548, 0.03321, 0.03696, 0.04637, 0.0467, 0.05007, 0.04881, 0.04904, 0.05273, 0.06039, 0.06121, 0.0657, 0.06233, 0.06072, 0.05993, 0.05047, 0.03927, 0.02834],
  [0.02649, 0.02321, 0.02205, 0.02248, 0.02255, 0.02372, 0.02875, 0.04461, 0.04421, 0.04918, 0.05597, 0.06202, 0.05026, 0.04716, 0.04401, 0.04034, 0.04166, 0.04529, 0.05316, 0.05597, 0.06027, 0.05304, 0.04646, 0.03712],
  [0.02394, 0.02046, 0.01733, 0.01577, 0.01489, 0.01438, 0.01407, 0.02413, 0.03203, 0.03633, 0.03644, 0.04151, 0.0418, 0.04496, 0.05644, 0.06759, 0.07461, 0.07036, 0.07045, 0.0681, 0.06425, 0.0591, 0.05169, 0.03936],
  [0.02996, 0.02532, 0.02095, 0.01641, 0.01663, 0.01356, 0.01258, 0.01581, 0.02889, 0.02889, 0.03153, 0.0402, 0.04053, 0.04361, 0.05261, 0.06001, 0.06456, 0.07191, 0.07204, 0.08036, 0.06922, 0.06806, 0.05499, 0.04136],
  [0.0257, 0.02067, 0.02048, 0.01326, 0.01138, 0.01044, 0.00929, 0.01172, 0.01623, 0.01875, 0.02926, 0.03863, 0.04334, 0.05687, 0.07902, 0.08113, 0.07987, 0.076, 0.07836, 0.06971, 0.06772, 0.05593, 0.04912, 0.03711],
  [0.02536, 0.01935, 0.01575, 0.0131, 0.01099, 0.01056, 0.00909, 0.0132, 0.01888, 0.02237, 0.02921, 0.04076, 0.05541, 0.06462, 0.0775, 0.07999, 0.08265, 0.08418, 0.07736, 0.0655, 0.05729, 0.05109, 0.04267, 0.03313],
  [0.01946, 0.01669, 0.01517, 0.01282, 0.01651, 0.01095, 0.01318, 0.02091, 0.0224, 0.02335, 0.02955, 0.03883, 0.05485, 0.06489, 0.0782, 0.08344, 0.08806, 0.08068, 0.07317, 0.06573, 0.0583, 0.04826, 0.03713, 0.02748],
  [0.0245, 0.02257, 0.0186, 0.0189, 0.01936, 0.01783, 0.01771, 0.03722, 0.03847, 0.04113, 0.06115, 0.06149, 0.04522, 0.04841, 0.05421, 0.05926, 0.06978, 0.06374, 0.0573, 0.05545, 0.05842, 0.04235, 0.0375, 0.02943],
  [0.02581, 0.02537, 0.0298, 0.02603, 0.02677, 0.02437, 0.02727, 0.03783, 0.04801, 0.04662, 0.05521, 0.05389, 0.04587, 0.04145, 0.04615, 0.05082, 0.05016, 0.06443, 0.05411, 0.05121, 0.04847, 0.04395, 0.04072, 0.03566],
  [0.02377, 0.02234, 0.02243, 0.02458, 0.02397, 0.02387, 0.02816, 0.02961, 0.04396, 0.04137, 0.04825, 0.05693, 0.04665, 0.04148, 0.04398, 0.04709, 0.05861, 0.06446, 0.0553, 0.05612, 0.0523, 0.05077, 0.0493, 0.0447],
];
const WEEKEND_RATIO = [0.97611, 0.97369, 0.93179, 0.83416, 1.00876, 0.96585, 1.12884, 1.07932, 0.99395, 1.07022, 1.02858, 1.01226];
const MONTH_SHARE = [0.05408, 0.04811, 0.07033, 0.05543, 0.07725, 0.09326, 0.14115, 0.17187, 0.11186, 0.06295, 0.05266, 0.06106];

const DAYS = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
const NO_DST = new Set(["America/Phoenix", "Pacific/Honolulu"]);
const pad2 = (n) => String(n).padStart(2, "0");

/**
 * A validation failure written for a homeowner.  Same convention as LoadFileError:
 * `message` is for logs, `userMessage` is a sentence the UI can show as-is.
 */
export class SynthLoadError extends Error {
  constructor(message, { code = "invalid", userMessage } = {}) {
    super(message);
    this.name = "SynthLoadError";
    this.code = code;
    this.userMessage = userMessage || "Those bills could not be used. Check the twelve numbers and try again.";
  }
}

function checkMonthly(monthlyKwh) {
  if (!Array.isArray(monthlyKwh) && !ArrayBuffer.isView(monthlyKwh)) {
    throw new SynthLoadError("monthlyKwh must be an array of 12 numbers", {
      code: "not-12", userMessage: "Please enter one number for each of the twelve months." });
  }
  if (monthlyKwh.length !== 12) {
    throw new SynthLoadError("monthlyKwh has " + monthlyKwh.length + " entries, need 12", {
      code: "not-12", userMessage: "Please enter one number for each of the twelve months." });
  }
  let total = 0;
  for (let m = 0; m < 12; m++) {
    const v = monthlyKwh[m];
    if (typeof v !== "number" || !Number.isFinite(v)) {
      throw new SynthLoadError("monthlyKwh[" + m + "] is not a finite number", {
        code: "not-number", userMessage: "One of the months is not a number. Use digits only, for example 640." });
    }
    if (v < 0) {
      throw new SynthLoadError("monthlyKwh[" + m + "] is negative", {
        code: "negative", userMessage: "A month's usage cannot be negative. If your bill shows a credit, enter 0 for that month." });
    }
    total += v;
  }
  if (!(total > 0)) {
    throw new SynthLoadError("monthlyKwh is all zero", {
      code: "all-zero", userMessage: "All twelve months are zero, so there is nothing to model. Enter the kWh from your bills." });
  }
}

/** "YYYY-MM" of the month before `now`, the last complete one. */
function lastCompleteMonth(now) {
  const y = now.getUTCFullYear(), m = now.getUTCMonth();   // m is 0-based: this month
  const py = m === 0 ? y - 1 : y, pm = m === 0 ? 12 : m;
  return py + "-" + pad2(pm);
}

/**
 * Turn twelve monthly totals into an hourly LoadSet.
 *
 * `monthlyKwh[0]` is January, whichever months the span covers: the twelve months
 * run from (endMonth - 11) to endMonth and each takes the entry of its calendar
 * month.
 */
export function synthesize({ monthlyKwh, tz = "America/Los_Angeles", endMonth, utilityId = null } = {}) {
  checkMonthly(monthlyKwh);
  const end = endMonth || lastCompleteMonth(new Date());
  if (!/^\d{4}-(0[1-9]|1[0-2])$/.test(end)) {
    throw new SynthLoadError("endMonth must look like YYYY-MM, got " + end, {
      code: "bad-month", userMessage: "The last month needs to be a year and month, such as 2026-08." });
  }
  const endY = +end.slice(0, 4), endM = +end.slice(5, 7);          // endM 1-12
  const observesDst = !NO_DST.has(tz);

  const ts = [], vals = [];
  const monthTotals = new Array(12).fill(0);
  let spanStart = null, spanEnd = null;

  for (let k = 11; k >= 0; k--) {
    // k months before endMonth
    let idx = endM - 1 - k, y = endY;
    while (idx < 0) { idx += 12; y--; }
    const cal = idx;                                               // 0-11 calendar month
    const dim = cal === 1 && ((y % 4 === 0 && y % 100 !== 0) || y % 400 === 0) ? 29 : DAYS[cal];
    const springDay = observesDst && cal === 2 ? +GBI.dstStartDate(y).slice(8, 10) : 0;
    const fallDay = observesDst && cal === 10 ? +GBI.dstEndDate(y).slice(8, 10) : 0;

    const start = ts.length;
    let sumW = 0;
    for (let d = 1; d <= dim; d++) {
      const dow = new Date(Date.UTC(y, cal, d)).getUTCDay();
      const weekend = dow === 0 || dow === 6;
      const prof = weekend ? WEEKEND[cal] : WEEKDAY[cal];
      const dayW = weekend ? WEEKEND_RATIO[cal] : 1;
      const dkey = y + "-" + pad2(cal + 1) + "-" + pad2(d);
      for (let h = 0; h < 24; h++) {
        if (d === springDay && h === 1) continue;                  // the label greenbutton.js drops that day
        const w = dayW * prof[h] * (d === fallDay && h === 1 ? 2 : 1);
        ts.push(dkey + "T" + pad2(h) + ":00");
        vals.push(w); sumW += w;
      }
    }
    // Scale this month's weights so the slots add up to the bill.
    const scale = monthlyKwh[cal] / sumW;
    for (let i = start; i < ts.length; i++) vals[i] *= scale;
    monthTotals[cal] = monthlyKwh[cal];
    if (k === 11) spanStart = ts[start];
    spanEnd = ts[ts.length - 1];
  }

  const kwh = Float64Array.from(vals);
  let totalKwh = 0;
  for (let i = 0; i < kwh.length; i++) totalKwh += kwh[i];

  return {
    meta: {
      source: "synthetic", tz, start: spanStart, end: spanEnd,
      nHours: kwh.length, totalKwh, intervalMinutes: 60, gapsFilled: [],
      utilityHint: utilityId || null,
      notes: [
        "Built from your twelve monthly bills, not from meter readings. Each month's total is exact; the hour-by-hour pattern is a typical home's.",
        "The typical pattern comes from one Southern California home with its electric car removed, so a home with big air-conditioning use, an EV or a pool will differ.",
        "Holidays are treated as ordinary weekdays.",
      ],
      monthlyKwh: Array.from(monthlyKwh),
    },
    ts, kwh, exportKwh: null,
  };
}

/**
 * Twelve monthly totals (Jan..Dec) from one annual figure, using the same
 * seasonal pattern the hourly shapes were built from.  Sums to `annualKwh`.
 */
export function seasonalSplit(annualKwh) {
  if (typeof annualKwh !== "number" || !Number.isFinite(annualKwh) || annualKwh <= 0) {
    throw new SynthLoadError("annualKwh must be a positive number", {
      code: "bad-annual", userMessage: "Enter your yearly usage in kWh as a number above zero, for example 7200." });
  }
  let t = 0;
  for (const s of MONTH_SHARE) t += s;
  return MONTH_SHARE.map((s) => annualKwh * s / t);
}

export default { synthesize, seasonalSplit, SynthLoadError };
